basket =["Banana","Apples","Oranges","Blueberries"]
basket.remove("Banana")
basket.remove("Blueberries")
basket.append("Kiwi")
basket.insert(0,"Apples")
print(basket)
count_apple=basket.count("Apples")
print(f"There are {count_apple} apples in the basket.")
basket.clear()
print(basket)